version: "3.9"
services:
    web:
        build: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend

    backend:
        build: 
            context: ./backend
            target: basic
        environment: 
            - PYTHONUNBUFFERED=1
            - FLASK_RUN_PORT=5000
        entrypoint: ["flask", "run"]