version: "3.9"
services:
    web:
        build:
            context: ./frontend
            args:
                - EXTERNAL_IP=${EXTERNAL_IP}
        ports:
            - "80:80"
        depends_on:
            - backend
            

    backend:
        build: 
            context: ./backend
            target: basic
        ports:
            - "5000:5000"
        environment: 
            - PYTHONUNBUFFERED=1
            - FLASK_RUN_PORT=5000
        entrypoint: ["flask", "run", "--host=0.0.0.0"]