version: '3'
services:
    web:
        build: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend

    backend:
        build: 
            context: ./backend
            target: basic
        environment: 
            - PYTHONUNBUFFERED=1